// Package schema generates the JSON Schema for model.Config
// (docs/config.schema.json, regenerated by `make schema` via
// daemon/cmd/schemagen) by reflecting over daemon/internal/model's
// types with github.com/invopop/jsonschema.
//
// model stays dependency-free (see its package doc comment) by never
// importing jsonschema itself; instead this package drives a
// Reflector.Mapper from the outside to fill in the two things plain
// struct-field reflection can't produce on its own:
//
//   - the named string enums (ControlKind, Gesture, TargetKind,
//     MediaCommand, ActionType, and api.ErrorCode) get an explicit
//     `enum`/`const`, sourced from their own package's accessors
//     (ControlKinds, Gestures, TargetKinds, MediaCommands, ActionTypes,
//     api.ErrorCodes) rather than duplicated here.
//   - model.Action is an interface; reflection can't see through it to
//     the 20 concrete params types actionRegistry knows about. Config,
//     Profile, and Binding below mirror model.Config/model.Profile/
//     model.Binding's actual on-disk JSON shape (see binding.go's
//     bindingJSON) but substitute actionDoc for the Action field, which
//     the Mapper replaces with a oneOf built by actionSchemas.
//
// This package also emits docs/openapi.json (openapi.go, M07), which is
// the one place daemon/internal/api is imported from outside itself --
// a one-way edge (schema -> api) that does not create a cycle and does
// not pull github.com/invopop/jsonschema into api or cmd/knobd (see
// specs/adr/0005-schema-generation-via-invopop.md).
package schema

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/invopop/jsonschema"

	"github.com/njeske/knobd/internal/api"
	"github.com/njeske/knobd/internal/model"
)

// Config, Profile, and Binding mirror the JSON shape
// model.Config/model.Profile/model.Binding actually (de)serialize to —
// see the package doc comment for why they exist instead of reflecting
// the model types directly. Every field here must be kept in sync with
// its model counterpart's json tags by hand; schema_test.go's structural
// coverage check catches a field added to the model side and forgotten
// here.
type Config struct {
	SchemaVersion   int                `json:"schemaVersion"`
	ActiveProfileID string             `json:"activeProfileId"`
	Profiles        []Profile          `json:"profiles"`
	AppMatchers     []model.AppMatcher `json:"appMatchers"`
	AppGroups       []model.AppGroup   `json:"appGroups"`
	Scenes          []model.Scene      `json:"scenes"`
}

// Profile mirrors model.Profile.
type Profile struct {
	ID          string    `json:"id"`
	DisplayName string    `json:"displayName"`
	Bindings    []Binding `json:"bindings"`
}

// Binding mirrors the shape model.Binding's MarshalJSON/UnmarshalJSON
// actually produce (daemon/internal/model/binding.go's bindingJSON) —
// model.Binding's own Go fields carry no json tags and an Action field
// reflection can't see through, so reflecting model.Binding directly
// would emit the wrong property names entirely.
type Binding struct {
	Layer   int           `json:"layer"`
	Control model.Control `json:"control"`
	Gesture model.Gesture `json:"gesture"`
	Action  actionDoc     `json:"action"`
}

// actionDoc stands in for model.Action. Its own shape is never
// reflected: mapper (below) intercepts this exact type before
// reflection looks at its fields and replaces it with a $ref to the
// "Action" oneOf definition actionSchemas builds.
type actionDoc struct{}

// mapper is the Reflector.Mapper shared by both reflection passes in
// Generate (the main Config walk and actionSchemas' per-action-type
// walk) — a value, not a method, so both *jsonschema.Reflector
// instances can use the exact same function.
func mapper(t reflect.Type) *jsonschema.Schema {
	switch t {
	case reflect.TypeOf(model.ControlKind("")):
		return enumSchema(model.ControlKinds())
	case reflect.TypeOf(model.Gesture("")):
		return enumSchema(model.Gestures())
	case reflect.TypeOf(model.TargetKind("")):
		return enumSchema(model.TargetKinds())
	case reflect.TypeOf(model.MediaCommand("")):
		return enumSchema(model.MediaCommands())
	case reflect.TypeOf(model.ActionType("")):
		return enumSchema(model.ActionTypes())
	case reflect.TypeOf(api.ErrorCode("")):
		return enumSchema(api.ErrorCodes())
	case reflect.TypeOf(api.EventType("")):
		return enumSchema(api.EventTypes())
	case reflect.TypeOf(actionDoc{}):
		return &jsonschema.Schema{Ref: "#/$defs/Action"}
	default:
		return nil
	}
}

// enumSchema builds a {"type":"string","enum":[...]} schema from a slice
// of any named string type.
func enumSchema[T ~string](values []T) *jsonschema.Schema {
	enum := make([]any, len(values))
	for i, v := range values {
		enum[i] = string(v)
	}
	return &jsonschema.Schema{Type: "string", Enum: enum}
}

// Generate returns the JSON Schema for model.Config as indented JSON
// with a trailing newline, matching daemon/internal/config.Save's
// on-disk style. It is deterministic: the same model produces
// byte-identical output every call (see schema_test.go's determinism
// check), which is what makes gating CI on a committed
// docs/config.schema.json meaningful.
func Generate() ([]byte, error) {
	// ExpandedStruct on the root reflector inlines Config's own
	// properties at the document root instead of leaving the root a
	// bare {"$ref": "#/$defs/Config"} — the conventional shape for a
	// schema meant to validate a whole file. The action reflector must
	// NOT set it: actionSchemas needs a real $ref (and the $defs entry
	// it points to) for each action's params type, not an inlined copy.
	root := (&jsonschema.Reflector{Anonymous: true, ExpandedStruct: true, Mapper: mapper}).
		Reflect(&Config{})
	// json-schema-to-typescript names the root export after Title, so
	// this must stay "Config" to match ui/'s generated type name (and
	// ui/src/api/client.ts's import of it) rather than a prose title.
	root.Title = "Config"
	root.Description = "knobd's on-disk configuration (~/.config/knobd/config.json). See daemon/internal/model.Config."

	oneOf, actionDefs := actionSchemas(&jsonschema.Reflector{Anonymous: true, Mapper: mapper})
	for name, def := range actionDefs {
		root.Definitions[name] = def
	}
	root.Definitions["Action"] = &jsonschema.Schema{OneOf: oneOf}

	data, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("schema: marshal: %w", err)
	}
	return append(data, '\n'), nil
}
