// Command codemap regenerates docs/codemap.md: a compact, always-fresh map
// of every package under daemon/internal and daemon/cmd — exported
// interfaces, struct fields, function/method signatures, package doc
// comments, test files, and an internal import graph.
//
// It exists so that planning a milestone doesn't require spawning an
// Explore agent to re-read every package from scratch each time (see
// specs/reference/codebase.md). It is a separate binary from cmd/knobd,
// like cmd/schemagen, so go/parser and go/doc never link into the daemon
// that actually ships.
//
// Output is deterministic (packages and declarations are sorted), so
// `make codemap` twice produces byte-identical output — CI enforces that
// docs/codemap.md is checked in and up to date the same way it does for
// the JSON schemas (see .github/workflows/ci.yml).
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/doc"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const modulePath = "github.com/njeske/knobd"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "codemap:", err)
		os.Exit(1)
	}
}

func run() error {
	root := flag.String("root", ".", "daemon module root (directory containing go.mod)")
	out := flag.String("o", "../docs/codemap.md", "path to write the generated document to")
	flag.Parse()

	pkgs, err := loadPackages(*root)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	buf.WriteString("# codemap\n\n")
	buf.WriteString("Generated by `make codemap` — do not edit by hand; CI fails if this " +
		"file is stale (see .github/workflows/ci.yml). Covers every package under " +
		"`daemon/internal` and `daemon/cmd`: exported interfaces, struct fields, " +
		"function/method signatures, package doc comments, test files, and each " +
		"package's internal import graph.\n\n" +
		"This is a signature index, not a substitute for reading the code — it deliberately " +
		"omits function bodies. See `specs/reference/codebase.md` for data flow, wiring, and " +
		"conventions this file can't capture.\n\n")

	for _, p := range pkgs {
		writePackage(&buf, p)
	}

	return os.WriteFile(*out, buf.Bytes(), 0o644)
}

type pkgInfo struct {
	importPath string // e.g. internal/midi, cmd/knobd
	dir        string
	doc        *doc.Package
	fset       *token.FileSet
	testFiles  []string
	testdata   []string // testdata/... paths referenced by _test.go files, deduped+sorted
	imports    []string // internal (module-local) imports, deduped+sorted
}

func loadPackages(root string) ([]*pkgInfo, error) {
	var dirs []string
	for _, base := range []string{"internal", "cmd"} {
		start := filepath.Join(root, base)
		err := walkGoDirs(start, &dirs)
		if err != nil {
			return nil, err
		}
	}
	sort.Strings(dirs)

	// Skip codemap's own package: it's a meta-tool, not project domain
	// code, and documenting itself here would be self-referential noise.
	filtered := dirs[:0]
	for _, d := range dirs {
		if filepath.Base(d) != "codemap" {
			filtered = append(filtered, d)
		}
	}
	dirs = filtered

	var pkgs []*pkgInfo
	for _, dir := range dirs {
		p, err := loadPackage(root, dir)
		if err != nil {
			return nil, fmt.Errorf("load %s: %w", dir, err)
		}
		if p != nil {
			pkgs = append(pkgs, p)
		}
	}
	return pkgs, nil
}

func walkGoDirs(start string, dirs *[]string) error {
	return filepath.Walk(start, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			return nil
		}
		entries, err := os.ReadDir(path)
		if err != nil {
			return err
		}
		for _, e := range entries {
			if !e.IsDir() && strings.HasSuffix(e.Name(), ".go") {
				*dirs = append(*dirs, path)
				break
			}
		}
		return nil
	})
}

var testdataRe = regexp.MustCompile(`testdata/[A-Za-z0-9_./-]+`)

func loadPackage(root, dir string) (*pkgInfo, error) {
	fset := token.NewFileSet()
	astPkgs, err := parser.ParseDir(fset, dir, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	// A directory can hold a "_test" external test package alongside the
	// main one (e.g. "midi" and "midi_test"); doc.New wants the main one.
	var astPkg *ast.Package
	for name, p := range astPkgs {
		if !strings.HasSuffix(name, "_test") {
			astPkg = p
			break
		}
	}
	if astPkg == nil {
		return nil, nil
	}

	rel, err := filepath.Rel(root, dir)
	if err != nil {
		return nil, err
	}
	importPath := filepath.ToSlash(rel)

	dpkg := doc.New(astPkg, modulePath+"/"+importPath, doc.AllDecls)

	info := &pkgInfo{
		importPath: importPath,
		dir:        dir,
		doc:        dpkg,
		fset:       fset,
	}

	importSet := map[string]bool{}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
			continue
		}
		path := filepath.Join(dir, e.Name())
		src, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		if strings.HasSuffix(e.Name(), "_test.go") {
			info.testFiles = append(info.testFiles, e.Name())
			for _, m := range testdataRe.FindAllString(string(src), -1) {
				info.testdata = append(info.testdata, m)
			}
		}
		f, err := parser.ParseFile(fset, path, src, parser.ImportsOnly)
		if err != nil {
			return nil, err
		}
		for _, imp := range f.Imports {
			p := strings.Trim(imp.Path.Value, `"`)
			if rest, ok := strings.CutPrefix(p, modulePath+"/"); ok {
				importSet[rest] = true
			}
		}
	}
	info.imports = sortedKeys(importSet)
	info.testFiles = sortedUnique(info.testFiles)
	info.testdata = sortedUnique(info.testdata)

	return info, nil
}

func sortedKeys(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func sortedUnique(in []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range in {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	sort.Strings(out)
	return out
}

func writePackage(buf *bytes.Buffer, p *pkgInfo) {
	fmt.Fprintf(buf, "## `%s`\n\n", p.importPath)

	if doc := strings.TrimSpace(p.doc.Doc); doc != "" {
		// First paragraph only — the full doc comment is in the source.
		para := strings.SplitN(doc, "\n\n", 2)[0]
		fmt.Fprintf(buf, "%s\n\n", strings.TrimSpace(para))
	}

	if len(p.imports) > 0 {
		fmt.Fprintf(buf, "**imports:** %s\n\n", strings.Join(backtickAll(p.imports), ", "))
	}

	// Interfaces first (what other packages are meant to depend on),
	// then structs, then everything else exported (funcs, consts, vars).
	sort.Slice(p.doc.Types, func(i, j int) bool { return p.doc.Types[i].Name < p.doc.Types[j].Name })

	var ifaces, structs, others []*doc.Type
	for _, t := range p.doc.Types {
		if isInterface(t) {
			ifaces = append(ifaces, t)
		} else if isStruct(t) {
			structs = append(structs, t)
		} else {
			others = append(others, t)
		}
	}

	for _, t := range ifaces {
		writeInterface(buf, t)
	}
	for _, t := range structs {
		writeStruct(buf, p.fset, t)
	}
	for _, t := range others {
		writeTypeDecl(buf, p.fset, t)
	}

	funcs := append([]*doc.Func{}, p.doc.Funcs...)
	sort.Slice(funcs, func(i, j int) bool { return funcs[i].Name < funcs[j].Name })
	if len(funcs) > 0 {
		buf.WriteString("**functions:**\n\n```go\n")
		for _, f := range funcs {
			buf.WriteString(sigOf(p.fset, f.Decl))
			buf.WriteString("\n")
		}
		buf.WriteString("```\n\n")
	}

	if len(p.doc.Consts) > 0 || len(p.doc.Vars) > 0 {
		var names []string
		for _, c := range p.doc.Consts {
			names = append(names, c.Names...)
		}
		for _, v := range p.doc.Vars {
			names = append(names, v.Names...)
		}
		sort.Strings(names)
		fmt.Fprintf(buf, "**consts/vars:** %s\n\n", strings.Join(backtickAll(names), ", "))
	}

	if len(p.testFiles) > 0 {
		fmt.Fprintf(buf, "**tests:** %s\n\n", strings.Join(backtickAll(p.testFiles), ", "))
	}
	if len(p.testdata) > 0 {
		fmt.Fprintf(buf, "**testdata used:** %s\n\n", strings.Join(backtickAll(p.testdata), ", "))
	}
}

func backtickAll(ss []string) []string {
	out := make([]string, len(ss))
	for i, s := range ss {
		out[i] = "`" + s + "`"
	}
	return out
}

func isInterface(t *doc.Type) bool {
	ts, ok := t.Decl.Specs[0].(*ast.TypeSpec)
	if !ok {
		return false
	}
	_, ok = ts.Type.(*ast.InterfaceType)
	return ok
}

func isStruct(t *doc.Type) bool {
	ts, ok := t.Decl.Specs[0].(*ast.TypeSpec)
	if !ok {
		return false
	}
	_, ok = ts.Type.(*ast.StructType)
	return ok
}

func writeInterface(buf *bytes.Buffer, t *doc.Type) {
	ts := t.Decl.Specs[0].(*ast.TypeSpec)
	it := ts.Type.(*ast.InterfaceType)

	fmt.Fprintf(buf, "### `%s` (interface)\n\n", t.Name)
	if doc := strings.TrimSpace(t.Doc); doc != "" {
		fmt.Fprintf(buf, "%s\n\n", strings.SplitN(doc, "\n\n", 2)[0])
	}
	buf.WriteString("```go\n")
	if it.Methods != nil {
		for _, m := range it.Methods.List {
			var typeBuf bytes.Buffer
			format.Node(&typeBuf, token.NewFileSet(), m.Type)
			typeStr := typeBuf.String()
			if len(m.Names) > 0 {
				// typeStr is "func(...) (...)"; drop the leading "func"
				// so it reads as a method signature: "Name(...) (...)".
				fmt.Fprintf(buf, "%s%s\n", m.Names[0].Name, strings.TrimPrefix(typeStr, "func"))
			} else {
				// embedded interface
				fmt.Fprintf(buf, "%s\n", typeStr)
			}
		}
	}
	buf.WriteString("```\n\n")
}

func writeStruct(buf *bytes.Buffer, fset *token.FileSet, t *doc.Type) {
	fmt.Fprintf(buf, "### `%s` (struct)\n\n", t.Name)
	if doc := strings.TrimSpace(t.Doc); doc != "" {
		fmt.Fprintf(buf, "%s\n\n", strings.SplitN(doc, "\n\n", 2)[0])
	}

	ts := t.Decl.Specs[0].(*ast.TypeSpec)
	// Print the struct type only (fields), not the surrounding "type X struct".
	var b bytes.Buffer
	b.WriteString("type ")
	b.WriteString(t.Name)
	b.WriteString(" ")
	format.Node(&b, fset, ts.Type)
	buf.WriteString("```go\n")
	buf.WriteString(b.String())
	buf.WriteString("\n```\n\n")

	if len(t.Methods) > 0 {
		methods := append([]*doc.Func{}, t.Methods...)
		sort.Slice(methods, func(i, j int) bool { return methods[i].Name < methods[j].Name })
		buf.WriteString("methods:\n\n```go\n")
		for _, m := range methods {
			buf.WriteString(sigOf(fset, m.Decl))
			buf.WriteString("\n")
		}
		buf.WriteString("```\n\n")
	}
}

func writeTypeDecl(buf *bytes.Buffer, fset *token.FileSet, t *doc.Type) {
	fmt.Fprintf(buf, "### `%s`\n\n", t.Name)
	if doc := strings.TrimSpace(t.Doc); doc != "" {
		fmt.Fprintf(buf, "%s\n\n", strings.SplitN(doc, "\n\n", 2)[0])
	}
	var b bytes.Buffer
	format.Node(&b, fset, t.Decl)
	buf.WriteString("```go\n")
	buf.WriteString(b.String())
	buf.WriteString("\n```\n\n")

	if len(t.Methods) > 0 {
		methods := append([]*doc.Func{}, t.Methods...)
		sort.Slice(methods, func(i, j int) bool { return methods[i].Name < methods[j].Name })
		buf.WriteString("methods:\n\n```go\n")
		for _, m := range methods {
			buf.WriteString(sigOf(fset, m.Decl))
			buf.WriteString("\n")
		}
		buf.WriteString("```\n\n")
	}
}

// sigOf renders a FuncDecl's signature line (receiver, name, params,
// results) with the body stripped.
func sigOf(fset *token.FileSet, decl *ast.FuncDecl) string {
	clone := *decl
	clone.Body = nil
	clone.Doc = nil
	var b bytes.Buffer
	format.Node(&b, fset, &clone)
	return strings.TrimSpace(b.String())
}
