/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the live audio graph
         * @description Live sinks, sources and streams, for the UI's target/app pickers. Streams carry their raw PipeWire property bag and which configured app matchers currently match them.
         */
        get: operations["getAudio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get what this daemon build actually supports
         * @description Which action types have a registered handler, which target kinds resolve, and which optional features (layers, scenes, learn) are available -- so the UI can reflect reality instead of hard-coding it.
         */
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the running configuration
         * @description Returns the configuration the daemon is running right now.
         */
        get: operations["getConfig"];
        /**
         * Replace the running configuration
         * @description Validates, applies to the running engine, and durably persists a new configuration. Takes effect immediately; no restart needed.
         */
        put: operations["putConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subscribe to live events
         * @description A Server-Sent Events stream: a hello frame, then a full state snapshot on connect, then state/config_changed/learn_input frames as they occur. See specs/adr/0004-ipc-over-unix-socket.md's Update (M07).
         */
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/learn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Arm MIDI learn
         * @description Arms learn mode: the next physical input is reported over GET /events as a learn_input event and NOT dispatched as an action. Disarms itself after the first captured input or the timeout, whichever comes first.
         */
        post: operations["startLearn"];
        /**
         * Disarm MIDI learn
         * @description Disarms learn mode if armed; a no-op otherwise.
         */
        delete: operations["stopLearn"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a point-in-time state snapshot
         * @description Device/audio/focus/profile status and every currently-bound control's resolved value. Pollable; see GET /events for a live push feed of the same shape.
         */
        get: operations["getState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Action: {
            /** @constant */
            type: "audio.duck_hold";
            params: components["schemas"]["AudioDuckHoldAction"];
        } | {
            /** @constant */
            type: "audio.solo_toggle";
            params: components["schemas"]["AudioSoloToggleAction"];
        } | {
            /** @constant */
            type: "knob.assign_focused_app";
            params: components["schemas"]["KnobAssignFocusedAppAction"];
        } | {
            /** @constant */
            type: "knob.clear";
            params: components["schemas"]["KnobClearAction"];
        } | {
            /** @constant */
            type: "knob.lock_toggle";
            params: components["schemas"]["KnobLockToggleAction"];
        } | {
            /** @constant */
            type: "layer.cycle";
            params: components["schemas"]["LayerCycleAction"];
        } | {
            /** @constant */
            type: "layer.latch";
            params: components["schemas"]["LayerLatchAction"];
        } | {
            /** @constant */
            type: "layer.momentary";
            params: components["schemas"]["LayerMomentaryAction"];
        } | {
            /** @constant */
            type: "media.now_playing";
            params: components["schemas"]["MediaNowPlayingAction"];
        } | {
            /** @constant */
            type: "media.seek";
            params: components["schemas"]["MediaSeekAction"];
        } | {
            /** @constant */
            type: "media.target_cycle";
            params: components["schemas"]["MediaTargetCycleAction"];
        } | {
            /** @constant */
            type: "media.transport";
            params: components["schemas"]["MediaTransportAction"];
        } | {
            /** @constant */
            type: "mic.push_to_mute";
            params: components["schemas"]["MicPushToMuteAction"];
        } | {
            /** @constant */
            type: "mic.push_to_talk";
            params: components["schemas"]["MicPushToTalkAction"];
        } | {
            /** @constant */
            type: "scene.apply";
            params: components["schemas"]["SceneApplyAction"];
        } | {
            /** @constant */
            type: "scene.save";
            params: components["schemas"]["SceneSaveAction"];
        } | {
            /** @constant */
            type: "shell.run";
            params: components["schemas"]["ShellRunAction"];
        } | {
            /** @constant */
            type: "sink.cycle_default";
            params: components["schemas"]["SinkCycleDefaultAction"];
        } | {
            /** @constant */
            type: "volume.adjust";
            params: components["schemas"]["VolumeAdjustAction"];
        } | {
            /** @constant */
            type: "volume.balance";
            params: components["schemas"]["VolumeBalanceAction"];
        } | {
            /** @constant */
            type: "volume.follow";
            params: components["schemas"]["VolumeFollowAction"];
        } | {
            /** @constant */
            type: "volume.mute_toggle";
            params: components["schemas"]["VolumeMuteToggleAction"];
        } | {
            /** @constant */
            type: "volume.set";
            params: components["schemas"]["VolumeSetAction"];
        };
        AppGroup: {
            id: string;
            displayName: string;
            matcherIds: string[];
        };
        AppMatcher: {
            id: string;
            displayName: string;
            binaries?: string[];
            appNames?: string[];
            nodeNames?: string[];
            desktopIds?: string[];
            mediaNameRx?: string;
        };
        AudioDevice: {
            ref: string;
            id: string;
            description: string;
            isDefault: boolean;
            volumePercent?: number;
            muted?: boolean;
        };
        AudioDuckHoldAction: {
            target: components["schemas"]["Target"];
            duckPercent: number;
        };
        AudioGraph: {
            /** Format: date-time */
            now: string;
            sinks: components["schemas"]["AudioDevice"][];
            sources: components["schemas"]["AudioDevice"][];
            streams: components["schemas"]["AudioStream"][];
        };
        AudioSoloToggleAction: {
            target: components["schemas"]["Target"];
        };
        AudioState: {
            connected: boolean;
            lastError?: string;
        };
        AudioStream: {
            ref: string;
            id: string;
            direction: string;
            displayName: string;
            binary?: string;
            binaryGuess?: string;
            appName?: string;
            nodeName?: string;
            desktopId?: string;
            mediaName?: string;
            corked: boolean;
            props: {
                [key: string]: string;
            };
            matcherIds?: string[];
            volumePercent?: number;
            muted?: boolean;
        };
        Binding: {
            layer: number;
            control: components["schemas"]["Control"];
            /** @enum {string} */
            gesture: "turn" | "press" | "hold" | "release" | "double_press" | "move";
            action: components["schemas"]["Action"];
        };
        Capabilities: {
            implementedActions: ("audio.duck_hold" | "audio.solo_toggle" | "knob.assign_focused_app" | "knob.clear" | "knob.lock_toggle" | "layer.cycle" | "layer.latch" | "layer.momentary" | "media.now_playing" | "media.seek" | "media.target_cycle" | "media.transport" | "mic.push_to_mute" | "mic.push_to_talk" | "scene.apply" | "scene.save" | "shell.run" | "sink.cycle_default" | "volume.adjust" | "volume.balance" | "volume.follow" | "volume.mute_toggle" | "volume.set")[];
            supportedTargetKinds: ("default_sink" | "sink" | "default_source" | "source" | "app" | "group" | "focused" | "all_streams")[];
            features: components["schemas"]["Features"];
        };
        Config: {
            schemaVersion: number;
            activeProfileId: string;
            profiles: components["schemas"]["Profile"][];
            appMatchers: components["schemas"]["AppMatcher"][];
            appGroups: components["schemas"]["AppGroup"][];
            scenes: components["schemas"]["Scene"][];
            media: components["schemas"]["MediaSettings"];
        };
        ConfigChanged: {
            revision: number;
        };
        Control: {
            /** @enum {string} */
            kind: "encoder" | "encoder_push" | "button" | "side_button" | "fader";
            index: number;
        };
        ControlState: {
            control: components["schemas"]["Control"];
            /** @enum {string} */
            gesture: "turn" | "press" | "hold" | "release" | "double_press" | "move";
            /** @enum {string} */
            actionType: "audio.duck_hold" | "audio.solo_toggle" | "knob.assign_focused_app" | "knob.clear" | "knob.lock_toggle" | "layer.cycle" | "layer.latch" | "layer.momentary" | "media.now_playing" | "media.seek" | "media.target_cycle" | "media.transport" | "mic.push_to_mute" | "mic.push_to_talk" | "scene.apply" | "scene.save" | "shell.run" | "sink.cycle_default" | "volume.adjust" | "volume.balance" | "volume.follow" | "volume.mute_toggle" | "volume.set";
            target?: components["schemas"]["Target"];
            resolved?: components["schemas"]["ResolvedTarget"];
        };
        DeviceState: {
            connected: boolean;
            name?: string;
            path?: string;
            lastError?: string;
        };
        ErrorResponse: {
            /** @enum {string} */
            code: "invalid_json" | "unsupported_schema_version" | "invalid_config" | "unavailable" | "internal" | "forbidden_origin" | "slow_consumer";
            message: string;
        };
        Event: {
            /** @enum {string} */
            type: "hello" | "state" | "config_changed" | "learn_input" | "error";
            seq: number;
            /** Format: date-time */
            now: string;
            hello?: components["schemas"]["Hello"];
            state?: components["schemas"]["State"];
            config?: components["schemas"]["ConfigChanged"];
            input?: components["schemas"]["LearnInput"];
            error?: components["schemas"]["ErrorResponse"];
        };
        Features: {
            layers: boolean;
            scenes: boolean;
            learn: boolean;
        };
        FocusState: {
            available: boolean;
            resourceClass?: string;
        };
        Hello: {
            protocolVersion: number;
            schemaVersion: number;
            flushIntervalMs: number;
        };
        KnobAssignFocusedAppAction: {
            stepPercent?: number;
        };
        KnobClearAction: Record<string, never>;
        KnobLockToggleAction: Record<string, never>;
        LayerCycleAction: {
            layerOrder?: number[];
        };
        LayerLatchAction: {
            layer: number;
        };
        LayerMomentaryAction: {
            layer: number;
        };
        LearnInput: {
            control: components["schemas"]["Control"];
            /** @enum {string} */
            suggestedGesture: "turn" | "press" | "hold" | "release" | "double_press" | "move";
            delta?: number;
            value?: number;
            /** Format: date-time */
            at: string;
        };
        LearnRequest: {
            timeoutMs?: number;
        };
        LearnState: {
            active: boolean;
            /** Format: date-time */
            expiresAt?: string;
        };
        MediaNowPlayingAction: {
            playerRef?: string;
        };
        MediaSeekAction: {
            seekMs: number;
            playerRef?: string;
        };
        MediaSettings: {
            ignorePlayers: string[];
        };
        MediaTargetCycleAction: Record<string, never>;
        MediaTransportAction: {
            /** @enum {string} */
            command: "play_pause" | "next" | "previous" | "shuffle_toggle" | "repeat_cycle";
            playerRef?: string;
        };
        MicPushToMuteAction: Record<string, never>;
        MicPushToTalkAction: Record<string, never>;
        Profile: {
            id: string;
            displayName: string;
            bindings: components["schemas"]["Binding"][];
        };
        ProfileState: {
            activeProfileId: string;
            activeLayer: number;
        };
        ResolvedTarget: {
            refs: string[];
            volumePercent?: number;
            muted?: boolean;
        };
        Scene: {
            id: string;
            displayName: string;
            entries: components["schemas"]["SceneEntry"][];
        };
        SceneApplyAction: {
            sceneId: string;
        };
        SceneEntry: {
            target: components["schemas"]["Target"];
            volumePercent: number;
            muted: boolean;
        };
        SceneSaveAction: {
            sceneId: string;
        };
        ShellRunAction: {
            command: string;
        };
        SinkCycleDefaultAction: {
            sinkNames: string[];
        };
        State: {
            /** Format: date-time */
            now: string;
            device: components["schemas"]["DeviceState"];
            audio: components["schemas"]["AudioState"];
            focus: components["schemas"]["FocusState"];
            profile: components["schemas"]["ProfileState"];
            learn: components["schemas"]["LearnState"];
            controls: components["schemas"]["ControlState"][];
        };
        Target: {
            /** @enum {string} */
            kind: "default_sink" | "sink" | "default_source" | "source" | "app" | "group" | "focused" | "all_streams";
            ref?: string;
        };
        VolumeAdjustAction: {
            target: components["schemas"]["Target"];
            stepPercent: number;
            curveExponent?: number;
        };
        VolumeBalanceAction: {
            target: components["schemas"]["Target"];
            step: number;
        };
        VolumeFollowAction: {
            target: components["schemas"]["Target"];
            minPercent?: number;
            maxPercent?: number;
        };
        VolumeMuteToggleAction: {
            target: components["schemas"]["Target"];
        };
        VolumeSetAction: {
            target: components["schemas"]["Target"];
            percent: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAudio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current audio graph. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudioGraph"];
                };
            };
            /** @description No audio provider is wired up, or the audio backend didn't answer in time. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current capabilities. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The running configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Config"];
                };
            };
            /** @description No configuration store is wired up. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    putConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Config"];
            };
        };
        responses: {
            /** @description Applied and persisted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed JSON, an unsupported schemaVersion, or a config that fails validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Applying or persisting failed. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No configuration store is wired up. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream of Event frames. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["Event"];
                };
            };
            /** @description Origin not on the allowlist. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No event hub is wired up. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    startLearn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearnRequest"];
            };
        };
        responses: {
            /** @description Learn mode armed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearnState"];
                };
            };
            /** @description Malformed request body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No learn controller is wired up. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    stopLearn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disarmed (or already inactive). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No learn controller is wired up. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["State"];
                };
            };
            /** @description No state provider is wired up. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
