/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Action =
  | {
      type: "audio.duck_hold";
      params: AudioDuckHoldAction;
    }
  | {
      type: "audio.solo_toggle";
      params: AudioSoloToggleAction;
    }
  | {
      type: "knob.assign_focused_app";
      params: KnobAssignFocusedAppAction;
    }
  | {
      type: "knob.clear";
      params: KnobClearAction;
    }
  | {
      type: "knob.lock_toggle";
      params: KnobLockToggleAction;
    }
  | {
      type: "layer.cycle";
      params: LayerCycleAction;
    }
  | {
      type: "layer.latch";
      params: LayerLatchAction;
    }
  | {
      type: "layer.momentary";
      params: LayerMomentaryAction;
    }
  | {
      type: "media.now_playing";
      params: MediaNowPlayingAction;
    }
  | {
      type: "media.seek";
      params: MediaSeekAction;
    }
  | {
      type: "media.target_cycle";
      params: MediaTargetCycleAction;
    }
  | {
      type: "media.transport";
      params: MediaTransportAction;
    }
  | {
      type: "mic.push_to_mute";
      params: MicPushToMuteAction;
    }
  | {
      type: "mic.push_to_talk";
      params: MicPushToTalkAction;
    }
  | {
      type: "scene.apply";
      params: SceneApplyAction;
    }
  | {
      type: "scene.save";
      params: SceneSaveAction;
    }
  | {
      type: "shell.run";
      params: ShellRunAction;
    }
  | {
      type: "sink.cycle_default";
      params: SinkCycleDefaultAction;
    }
  | {
      type: "volume.adjust";
      params: VolumeAdjustAction;
    }
  | {
      type: "volume.balance";
      params: VolumeBalanceAction;
    }
  | {
      type: "volume.follow";
      params: VolumeFollowAction;
    }
  | {
      type: "volume.mute_toggle";
      params: VolumeMuteToggleAction;
    }
  | {
      type: "volume.set";
      params: VolumeSetAction;
    };

/**
 * knobd's on-disk configuration (~/.config/knobd/config.json). See daemon/internal/model.Config.
 */
export interface Config {
  schemaVersion: number;
  activeProfileId: string;
  profiles: Profile[];
  appMatchers: AppMatcher[];
  appGroups: AppGroup[];
  scenes: Scene[];
  media: MediaSettings;
}
export interface Profile {
  id: string;
  displayName: string;
  bindings: Binding[];
}
export interface Binding {
  layer: number;
  control: Control;
  gesture: "turn" | "press" | "hold" | "release" | "double_press" | "move";
  action: Action;
}
export interface Control {
  kind: "encoder" | "encoder_push" | "button" | "side_button" | "fader";
  index: number;
}
export interface AudioDuckHoldAction {
  target: Target;
  duckPercent: number;
}
export interface Target {
  kind: "default_sink" | "sink" | "default_source" | "source" | "app" | "group" | "focused" | "all_streams";
  ref?: string;
}
export interface AudioSoloToggleAction {
  target: Target;
}
export interface KnobAssignFocusedAppAction {
  stepPercent?: number;
}
export interface KnobClearAction {}
export interface KnobLockToggleAction {}
export interface LayerCycleAction {
  layerOrder?: number[];
}
export interface LayerLatchAction {
  layer: number;
}
export interface LayerMomentaryAction {
  layer: number;
}
export interface MediaNowPlayingAction {
  playerRef?: string;
}
export interface MediaSeekAction {
  seekMs: number;
  playerRef?: string;
}
export interface MediaTargetCycleAction {}
export interface MediaTransportAction {
  command: "play_pause" | "next" | "previous" | "shuffle_toggle" | "repeat_cycle";
  playerRef?: string;
}
export interface MicPushToMuteAction {}
export interface MicPushToTalkAction {}
export interface SceneApplyAction {
  sceneId: string;
}
export interface SceneSaveAction {
  sceneId: string;
}
export interface ShellRunAction {
  command: string;
}
export interface SinkCycleDefaultAction {
  sinkNames: string[];
}
export interface VolumeAdjustAction {
  target: Target;
  stepPercent: number;
  curveExponent?: number;
}
export interface VolumeBalanceAction {
  target: Target;
  step: number;
}
export interface VolumeFollowAction {
  target: Target;
  minPercent?: number;
  maxPercent?: number;
}
export interface VolumeMuteToggleAction {
  target: Target;
}
export interface VolumeSetAction {
  target: Target;
  percent: number;
}
export interface AppMatcher {
  id: string;
  displayName: string;
  binaries?: string[];
  appNames?: string[];
  nodeNames?: string[];
  desktopIds?: string[];
  mediaNameRx?: string;
}
export interface AppGroup {
  id: string;
  displayName: string;
  matcherIds: string[];
}
export interface Scene {
  id: string;
  displayName: string;
  entries: SceneEntry[];
}
export interface SceneEntry {
  target: Target;
  volumePercent: number;
  muted: boolean;
}
export interface MediaSettings {
  ignorePlayers: string[];
}
